#+TITLE:       Retrieving properties of ice-clouds from combined RADAR and passive microwave and sub-millimeter observations
#+AUTHOR:      Simon Pfreunschuh, Patrick Eriksson, Stefan Buehler, Manfred Brath, @@latex:\\@@ David Duncan, Robin Eklund
#+EMAIL:       simon.pfreundschuh@chalmers.se
#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{natbib}
#+LaTeX_HEADER: \usepackage{siunitx}
#+LaTeX_HEADER: \usepackage{subcaption}

  
* Introduction

   Ice clouds are an important component of the Earth's atmosphere and as such
   affect its weather and climate. Through reflection of incoming short-wave
   radiation and outgoing long-wave radiation, ice clouds influence the Earth's
   energy budget. Furthermore, due to their role in the global hydrological
   cycle and because of their relation to the dynamics of the atmosphere,
   observations of ice clouds provide important information to constrain the
   state of the atmosphere in forecasting models citep:geer or to validate
   predictions from climate models citep:waliser09.

   Despite the importance of observations of ice clouds for climate and weather
   prediction, the insufficiency of the current, global earth observation system
   to provide accurate information on concentrations of ice in the atmosphere
   has been put forward by several studies citep:eliasson11,duncan18a.
   Ultimately, this insufficiency is rooted in the large variability of
   concentrations, shapes and sizes in which ice in the atmosphere occurs,
   making it very difficult to accurately determine bulk-properties such
   as mass or number density using remote sensing techniques.

   The sensitivity of a remote sensing system to ice particles of given size is
   determined mainly by its observing frequencies. The interaction of radiation
   with ice particles is strongest for sizes roughly equal to the wavelength
   $\lambda$ of the radiation but decreases rapidly for smaller sizes. On the
   other hand, particles larger than one wavelength interact with the radiation
   strong enough that their presence quickly leads to saturation of the signal
   and thus loss of sensitivity inside and at the bottom of clouds.

   Since radiation at different frequencies is sensitive to ice crystals of
   different sizes, combining observations from across the electromagnetic
   spectrum can improve retrievals, allowing a larger part of the ice to be
   actively sensed as opposed to inferred based on a priori assumptions on the
   distribution of particle sizes. Even the combination of different types of
   observations at similar wavelengths, for example active and passive, can
   potentially improve a retrieval by providing additional information on the
   background state of the atmosphere.

   Of recent satellite missions that observe clouds, the A-train satellite
   constellation is certainly the most prominent. The constellation comprises
   several active and passive sensors observing the Earth only few minutes apart
   and has led to great advances in our ability to observe atmospheric ice at
   global scale. In particular, the CloudSat citep:stephens02 mission carrying
   the Cloud Profiling Radar (CPR, cite:tanelli08) has delivered unprecedented
   observations of the vertical distribution of ice in the atmosphere
   citep:austin09. Yet still, even the vertically resolved observations from a
   cloud radar possess only limited sensitivity to small ice particles and are
   unable to discern cloud microphysical properties. The low sensitivity of
   CloudSat to thin ice clouds has lead to the development of synergetic
   retrievals that combine CPR observations with other A-train sensors. The
   DARDAR-CLOUD citep:cazenave18 and CloudSat 2C-Ice citep:deng15 products, for
   example, both combine CPR observations with observations from the
   Cloud-Aerosol Lidar with Orthogonal Polarization (CALIOP, cite:winker07) to
   increase sensitivity to thin Cirrus clouds.

   Another perspective on ice particles in the atmosphere is provided by the
   Global precipitation measurement (GPM) mission citep:hou14. The backbone of
   the GPM mission is formed by its core observatory satellite, which carries
   the Dual-frequency Precipitation Radar (DPR) and the GPM Microwave Imager (GMI).
   Combined observations from DPR and GMI are used to retrieve vertically
   resolved concentrations of precipitating, liquid and frozen hydrometeors. The
   precipitation profiles retrieved from the combined active and passive
   observations from the core observatory are then used to constrain
   the passive-only precipitation profile retrievals from the other passive
   radiometers in the constellation citep:kummerow15.

   By virtue of their observing frequencies, the combined A-train products
   mentioned above and GPM essentially measure different types of atmospheric
   ice. CloudSat CPR observations, when combined with observations from the IR
   and optical regime ($\lambda < \SI{10}{\micro \meter}$) are best suited for
   the observation of comparably small, non-precipitating ice particles,
   typically referred to as cloud ice. The passive radiometers of the GPM
   constellation, are limited in their sensitivity to large, precipitating
   particles due to their limitation to microwave frequencies at and below
   $\SI{187}{\giga \hertz}$ ($\lambda < \SI{16}{\milli \meter}$).

   With the launch of the Ice Cloud Image (ICI) on board the second generation
   of meteorological, operational, polar-orbiting satellites (MetOp SG) planned
   from 2022, a new frequency range will become available to study ice in the
   troposphere. ICI will provide observations at 22 channels ranging from $187$
   to $\SI{664}{\giga \hertz}$ in frequency ($\SI{16}{\milli \meter} \leq
   \lambda \leq \SI{0.45}{\milli \meter}), and thus close the gap between
   observations in the traditional microwave region on the one hand and IR and
   optical observation on the other.

   Both, the A-train-based and GPM synergetic retrievals, demonstrate the
   potential of combining observations at different wavelengths as well as
   observations from active and passive sensors to improve the measurements of
   atmospheric ice from space. With the upcoming launch of ICI on board the
   MetOpSG satellites a new frequency range will become available to observe ice
   in the atmosphere and with that new opportunities for synergistic
   retrievals combining sub-millimeter observations with observations from other
   domains of the electromagnetic spectrum.

   While several studies so far have addressed the information content
   of sub-millimeter observations citep:grutzun18,birman17, only one
   early study on sub-millimeter radiometry citep:evans98 considers the
   combination with radar observations.

   In this study, we set out to investigate the potential of synergistic
   retrievals that combine ICI observations with that of a CPR-type cloud
   radar and additional passive microwave channels from the Microwave Imager
   (MWI), that will be flown together with ICI. In particular, we address
   the question to which extent complementary information content of the combined
   observations can help to constrain cloud microphysics. Furthermore, the
   technical feasibility of such retrievals is demonstrated by presenting a
   variational retrieval algorithm which is applied to retrieve cloud properties
   from simulated observations of cloud scenes from high-resolution climate
   model data.


* Methods and data

  This study aims to investigate the potential of synergistic retrievals of ice
  hydrometeors using observations from the ICI and MWI passive radiometers
  combined with a hypothesized W-band cloud radar. For this, cloud scenes from a
  high-resolution climate model are used to produce synthetic observations using
  radiative transfer simulations. The combined cloud retrieval algorithm is then
  applied to the synthetic observations and results compared to the reference
  cloud scenes.

  This section introduces the reference cloud scenes and the radiative transfer
 code used to generate the synthetic observations. This is followed by a
 description of the assumed sensor setup and the cloud retrieval algorithm.

** Reference cloud scenes

    As test scenes for the cloud retrieval, high-resolution climate model data
    from the Global Environmental Multiscale Model (GEM, cite:cote98) are used.
    The scenes have been produced for a validation campaign for the upcoming
    EarthCare satellite mission and can thus be expected to represent clouds
    with a degree of realism that is sufficient for the development and
    evaluation of a cloud retrieval algorithm. The use of model scenes as test
    data has the advantage of providing full knowledge and control of the true
    atmospheric state and thus allow for accurate characterization of retrieval
    performance. An overview over the two test scenes that will be used to test
    the retrieval is given in Figure \ref{fig:overview}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/scene_overview.png}
    \caption{The distribution of total hydrometeor mass content in the two
    cloud scenes used to test the retrieval. Colored lines show the
     $m = 10^{-5} \SI{}{\kg \per \meter \cubed}$ contour for different
     hydrometeor species.}
    \label{fig:overview}
    \end{figure}

    The GEM model uses the Milbrandt-Yau two-moment scheme citep:milbrandtyau05
    to predict distributions of liquid and frozen particles in the atmosphere.
    Clouds and precipitation are represented using 6 different hydrometeor
    classes: two liquid (rain and liquid cloud particles) and four
    frozen types (cloud ice, snow, hail and graupel). The bulk-microphysics
    scheme used in the model predicts number and mass density for each of the
    hydrometeor species. From the number and mass concentrations the full
    particle size distribution (PSD) can be prognosed using a species-dependent
    parametrization and mass-size relationship. To visualize the microphysical
    assumptions for the frozen hydrometeors, radomly-drawn realizations of
    particle size distributions from the test scenes together with
    the particle shapes are shown in Figure \ref{fig:gem_psds}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/gem_hydrometeors.png}
    \caption{Realizations of particle size distributions from the cloud scenes used in
    this study. Grey curves show 100 particle size distributions drawn randomly from
    grid points with a mass concentration higher than $10^{-6}$. Colored curves show the
    PSD for the prognosed for the mean of the 100 randomly drawn number and mass
    concentrations.}
    \label{fig:gem_psds}
    \end{figure}

** Radiative transfer simulations

   Version 2.3.1243 of the Atmospheric Radiative Transfer Simulator (ARTS,
   cite:arts18) is used for all simulations presented in this study. ARTS has
   recently been extended with a single-scattering radar solver that can be used
   to simulate radar reflectivities. Likewise, interfaces to state-of-the-art
   scattering solvers for the simulation of passive radiances in cloudy
   atmospheres have been added. Together with the recently developed ARTS single
   scattering database citep:ssdb,eriksson18, ARTS has grown to become an
   integrated tool for the study of of microwave and sub-millimeter observations
   of clouds. A recent closure study using CloudSat CPR and GMI observations has
   shown that ARTS is capable of reproducing the scattering signal observed from
   clouds at high microwave frequencies ($\SI{183}{\giga \hertz}$),
   demonstrating ARTS' capability produce realistic simulations of clouds
   observed at microwave frequencies.
   
   For the simulation of passive radiances a hybrid solver is used that combines
   the DISORT scattering solver to simulate scattering interaction of radiation
   with cloud particles and ARTS built-in line-by-line solver. Simulations
   are performed assuming an ocean surface with emissivities calculated using
   the TESSEM sea-surface emissivity model. Polarization is neglected in all
   simulations performed in this study.
   

** Sensor configuration
\label{sec:sensors}
   
  For the simulated observations, we assume perfectly co-located observations of
  a W-band cloud radar combined with observations from the ICI and MWI
  radiometers. The beams from all three instruments channels are assumed to be
  perfectly coincident pencil beams.

  ICI observations are simulated by performing a single, non-polarized radiative
  transfer simulation located at the center of each side band and averaging the
  resulting brightness temperatures. Only a single simulation is performed for
  channels with multiple polarizations but to compensate the noise of the
  corresponding channel is reduced by a factor of $\sqrt{2}$.

  MWI observations are simulated in a similar manner, but using only channels
  with frequencies larger than or equal to $\SI{89}{\giga \hertz}$, due the very
  large footprint of the lower-frequency channels.

  For both, MWI and ICI, an off-nadir angle of $\SI{48}{\degree}$ is assumed. 
  The frequencies of the channels simulated for ICI and MWI are presented in
  table \ref{tab:channels}.

      \begin{table}[h!]
      \caption{Simulated channels of the MWI and ICI radiometers.}
      \label{tab:channels}
      \begin{subtable}[t]{0.45\textwidth}
      \caption{MWI}
          \resizebox{\textwidth}{!}{%
          \begin{tabular}{c|r|r}
          Channel & Freq. [GHz] & Noise [K]\\
          \hline
          MWI-8  & $89$              & $1.1$ \\
          MWI-9  & $118.75 \pm 3.2$  & $1.3$ \\
          MWI-10 & $\pm 2.1$         & $1.3$ \\
          MWI-11 & $\pm 1.4$         & $1.3$ \\
          MWI-12 & $\pm 1.2$         & $1.3$ \\
          MWI-13 & $165.5 \pm 0.75$  & $1.3$ \\
          MWI-14 & $183.31 \pm 7.0$  & $1.2$ \\
          MWI-15 & $ \pm 6.1$        & $1.2$ \\
          MWI-16 & $ \pm 4.9$        & $1.2$ \\
          MWI-17 & $ \pm 3.4$        & $1.2$ \\
          MWI-18 & $ \pm 2.0$        & $1.3$ \\
          \end{tabular}%
          }%
      \end{subtable}\hfill
      \begin{subtable}[t]{0.45\textwidth}
      \caption{ICI}
          \resizebox{\textwidth}{!}{%
          \begin{tabular}{c|r|r}
          Channel & Freq. [GHz] & Noise [K] \\
          \hline
          ICI-1  & $183.31 \pm 7.0$ & $0.8$\\
          ICI-2  & $       \pm 3.4$ & $0.8$\\
          ICI-3  & $       \pm 2.0$ & $0.8$\\
          ICI-4  & $243    \pm 2.5$ & $\frac{0.7}{\sqrt{2}}$\\
          ICI-5  & $325.15 \pm 9.5$ & $1.2$\\
          ICI-6  & $       \pm 3.5$ & $1.3$\\
          ICI-7  & $       \pm 1.5$ & $1.5$\\
          ICI-8  & $448    \pm 7.2$ & $1.4$\\
          ICI-9  & $       \pm 3.0$ & $1.6$\\
          ICI-10 & $       \pm 1.4$ & $2.0$\\
          ICI-11 & $664    \pm 4.2$ & $\frac{1.6}{\sqrt{2}}$\\
          \end{tabular}}
      \end{subtable}
      \end{table}

     The frequency for the cloud radar is chosen to be $\SI{94}{\giga\hertz}$
     similar to CloudSat CPR. The vertical resolution is assumed to be
     $\SI{500}{\meter}$ ranging from $0$ to $\SI{20}{\kilo \meter} in altitude.
     The minimum sensitivity is assumed to be $-\SI{30}{\deci \bel}\text{Z}$ and
     the noise at each range gate is assumed independent with standard deviation
     $0.5$. For simplicity, the same incidence angle as for the passive
     radiometers is used, assuming the radar observations at nadir can be
     remapped to the lines of sights of the passive beams.

** Retrieval algorithm

   The proposed 1-dimensional, variational cloud retrieval algorithm uses the
   optimal estimation formalism developed by cite:rodgers00. This means that the
   retrieved state $\mathbf{x} \in \mathrm{R}^n$ is determined by fitting a
   forward model $F : \mathbf{R}^n \rightarrow \mathbf{R}^m$ to a set of
   observations $\mathbf{y} \in \mathrm{R}^m$. The best fist is determined by
   minimizing a cost function of the form

    \begin{align}
    l(\mathbf{x}, \mathbf{y}) \propto
     \left(\mathbf{F}(\mathbf{x} - \mathbf{y} \right )
      \mathbf{S}_e^{-1} 
      \left ( \mathbf{F}(\mathbf{x}) - \mathbf{y} \right)
    + \left ( \mathbf{x} - \mathbf{x}_a \right )
     \mathbf{S}^{-1}_a 
     \left ( \mathbf{x} - \mathbf{x}_a \right ),
    \end{align}

    which corresponds to the negative log-likelihood of the Bayesian a
    posteriori distribution of the state $\mathbf{x}$ assuming zero-mean
    Gaussian measurement error with covariance matrix $\mathbf{S}_e$ and
    Gaussian a priori distribution with mean $\mathbf{x}_a$ and covariance
    matrix $\mathbf{S}_a$.

    The joint observation vector $\mathbf{y}$ simply consists of the
    concatenated observation vectors from each of the instruments:

     \begin{align}
     \mathbf{y} &= \left [ \begin{array}{c} \mathbf{y}_\text{MWI} \\ 
     \mathbf{y}_\text{ICI} \\ \mathbf{y}_\text{CPR} \end{array} \right ] 
     \end{align}

     Measurement errors are assumed to be independently Gaussian-distributed
     with standard deviations according to the noise characteristics given
     in Section \ref{sec:sensors}.

    The retrieved atmospheric state $\mathbf{x}$ consists of the distribution
    of a liquid and a frozen hydrometeor species and atmospheric humidity along
    a 1-dimensional atmospheric column coincident with antenna beams.

    To represent the distributions of hydrometeors in the atmospheric column the
    normalized modified gamma distribution approach proposed by cite:delanoe05
    is used. This means that at each point in the atmospheric column the
    distribution of a given hydrometeor species is defined by its concentration
    coefficient $N_0^*$ and corresponding mass-weighted mean size diamter $D_m$.
    For the shape parameters $\alpha$ and $\beta$ for frozen hydrometeors the
    same values as in version 2 of the DARDAR-CLOUD product citep:cazenave18 are
    used. For liquid hydrometeors, the shape parameters are chosen so that they
    are equivalent to the shape used by the GEM model for rain drops. Figure
    \ref{psds_retrieval} displays the resulting PSD shapes and corresponding
    parameter
    values.

    \begin{figure}
    \centering
    \includegraphics[width = 0.5\textwidth]{../plots/psds_retrieval}
    \caption{PSD parametrizations for frozen and liquid hydrometeors
     used in the cloud retrieval.}
    \label{fig:psds_retrieval}
    \end{figure}

    For frozen hydrometeors, the temperature-dependent a priori mean state
    is determined using the relation from cite:delanoe14:
    
    \begin{align}
    N_0^* &= \exp (-0.076586 \cdot t + 17.948)
    \end{align}
    
    The a priori state for $D_m$ for frozen hydrometeors is chosen so that the a
    priori mass density is $10^{-5} \SI{}{\kilo \gram \per \cubic \meter} $
    For liquid hydrometeors, a fixed value for $N_0^*$ of $10^6\SI[mode =
    text]{m^{-4}}$ is assumed and the a priori profile for $D_m$ is determined
    similarly as for frozen hydrometeors
    
    As an additional modeling constraint, the retrieval of liquid and frozen
    hydrometeors are restricted to below and above the melting layer,
    respectively.
    
    



    


    point in the atmospheric column hydrometeor distributions are represented
    
    
    Several other retrieval algorithms have been developed to retrieve cloud
    properties from sub-millimeter observations
    citep:jimenez03,evans05,buehler12,brath18a. To date, all cloud retrievals
    developed for the sub-millimeter domain rely on databases of simulated
    observations. One reason for this are the high computational costs of
    performing radiative transfer simulations of clouds in the sub-millimeter
    domain. Only with recent developments of the ARTS RT code, it has become
    possible to compute approximate Jacobians of the observation operator with
    sufficiently low computational effort to make variational retrievals
    tractable.

    The variational retrieval algorithm developed for this study uses the
    optimal estimation method (OEM) developed by cite:rodgers00 to determine a
    most likely atmospheric state $\mathbf{x} \in \mathrm{R}^n$ given an
    observation vector $\mathbf{y} \in \mathrm{R}^m$. The retrieved state
    $\mathbf{x}$ is found by minimizing the negative log-likelihood
    of the observed $\mathbf{y}$ with respect to $\mathbf{x}$. The function $l$
    is the log-likelihood of the Bayesian a posteriori probability of the state
    $\mathbf{x}$ given the observations $\mathbf{y}$ under the assumption of a
    Gaussian a priori distribution $\mathcal{N}(\mathbf{x}_a, \mathbf{S}_x)$ and
    Gaussian measurement errors $\mathcal{N}(\mathbf{0}, \mathbf{S}_e)$.

* Retrieval formulation

    To arrive at the full formulation of the retrieval algorithm it necessary to
    specify the form of the measurement vector $\mathbf{y}$ and associated
    uncertainties $\mathbf{S}_e$, the form of the state vector $\mathbf{x}$ and
    associated uncertainties $\mathbf{S}_a$ as well as the forward model $F$
    that is used to simulate observations corresponding to a given atmospheric
    state.
    
** Observations
     
     The observations used in the retrieval are simulated observations from two
     passive radiometers similar to the ICI and MWI radiometers combined with
     those from a W-band cloud radar similar to CloudSat CPR.

     The combined observation vector $\mathbf{y}$ is obtained by simple
     concatenation of the single-instrument observations $\mathbf{y}_\text{MWI},
     \mathbf{y}_\text{ICI}, \mathbf{y}_{CPR}$:

     \begin{align}
     \mathbf{y} &= \left [ \begin{array}{c} \mathbf{y}_\text{MWI} \\ 
     \mathbf{y}_\text{ICI} \\ \mathbf{y}_\text{CPR} \end{array} \right ] 
     \end{align}

     We will also perform retrievals using only radar observations and
     using only the passive radiometer observations, respectively. Those
     will be referred to as radar-only (RO) and passive-only (PO) retrievals,
     respectively.

     \begin{align}
     \mathbf{y}_\text{RO} &= \left [\begin{array}{c} \mathbf{y}_\text{CPR}
      \end{array} \right ]  \\
     \mathbf{y}_\text{PO} &= \left [ \begin{array}{c} \mathbf{y}_\text{MWI} \\ 
     \mathbf{y}_\text{ICI} \end{array} \right] 
     \end{align}

     Regarding measurement errors, only random sensor noise is considered 
     in this study. For the passive radiometers, the measurement error is
     assumed to be independent and Gaussian with standard deviations
     equal to the noise specifications of each sensor channel.
     For the radar, the measurement error at each range gate is assumed
     to be Gaussian with standard deviation of $\SI{1}{\decibel}\text{Z}$.

     
** State space

     The state space for the retrieval consists of the humidity profile
     of the atmosphere, together with the distributions of two hydrometeor
     classes, one for frozen and one for liquid hydrometeors.

     For both, liquid and frozen hydrometeors, the two-moment parametrization
     proposed by cite:delanoe05,delanoe14 is used. That is, for each volume
     in the atmospheric column the distribution of hydrometeors is determined
     by the values of the concentration parameter $N_0^*$ and the mass-weighted
     mean diameter $D_m$. The shape parameters $\alpha$ and $\beta$ used
     for liquid and frozen hydrometeors are given in
     Table \ref{tab:shape_parameters}.

       \begin{table}[h!]
     \caption{Shape parameters of the normalized Modified Gamma Distribution
      used to represent hydrometeors.}\label{tab:shape_parameters}
      \centering
     \begin{tabular}{|c|cc|}
     \hline
     Hydrometeor type & $\alpha$ & $\beta$ \\
     \hline
     \hline
     Frozen & -1 & 3 \\
     Liquid & 2 & 1 \\
     \hline
     \end{tabular}
     \end{table}
     
   
* Results

** Homogeneous cloud layer

    As a preliminary study of the information content in combined radar
    and passive microwave and sub-millimeter measurement, observations
    of a homogeneous cloud layer with given mass density $m$  and mass weighted
    mean diameter $D_m$ are considered. For given $D_m$, the mass density of
    ice particles contained in an atmospheric volume is proportional to the
    concentration parameter $N_0^*$:

    \begin{align}
    N_0^* &= \frac{4 ^4}{\pi \rho} \frac{m}{D_m^4}
    \end{align}

    where $rho$ is the density of ice. Simulated observations of the homogeneous
    cloud layer for varying mass density and $D_m$ thus represent the effect of
    the two moments of the D14 PSD on the observations.

    We first address the question to what extent the observations from radar and
    passive radiometers constrain the two moments of the PSD. Figure
    \ref{fig:isolines} displays the simulated cloud signal $\Delta T_B =
    y_\text{clearsky} - y_\text{cloudy}$, i.e. the difference of clear-sky and
    cloudy-sky radiances, for selected radiometer channels together with
    isolines of the radar reflectivity at the center of the cloud layer. A
    necessary condition for a combined retrieval to retrieve the two moments of
    the PSD is that isolines of the combined observations cross each other. The
    first row of panels, that displays simulated radar reflectivities with the
    cloud signal seen by the MWI radiometer, thus indicates low complementary
    information content in the MWI observations with respect to the radar
    observations since radar and radiometer isolines run essentially parallel.
    In contrast to that, the isolines of the ICI observations, displayed in the
    second row of panels, show a higher degree of independence of the radiometer
    observations from the radar observations, thus indicating higher
    complementary information content.
    
    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/contours}
    \caption{Simulated observations of a homogeneous cloud layer with
    varying mass density $m$ and mass-weighted mean diameter $D_m$. The panels
    display the radar reflectivity in dBZ at the cloud center overlaid on the
    cloud signal measured by selected radiometer channels of the MWI radiometer
    (first row) and the ICI radiometer (second row).}
    \label{fig:isolines}
    \end{figure}

    Secondly, we investigate the impact of the assumed ice particle shape on the
    observations. For this, simulations of the same homogeneous cloud layer
    described above are performed for a range of particle shapes from the ARTS
    SSDB. To compare the effect of the particle shape on the simulated
    observations, principal component analysis (PCA) is used to determine the
    two axes of highest variance for all simulated observations. Scatter plots
    of the simulated observation projectet into the space spanned by the two
    axes of maximum variance are displayed in Figure \ref{fig:pca}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/pca.pdf}
    \caption{Simulated observations for varying mass density and
    mass-weighted mean diameter of a homogeneous cloud layer projected
    onto the two axes of maximum variance for a range of particle shapes
    taken from the ARTS SSDB.}
    \label{fig:pca}
    \end{figure}
    



** Retrieval results

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/retrieval_results_a}
    \caption{Retrieval results for the first reference cloud scene.}
    \label{fig:pca}
    \end{figure}

* Discussion


* Conclusion
   
    


bibliographystyle:apalike 
bibliography:/home/simonpf/papers/references.bib
