#+TITLE:       Retrieving properties of ice-clouds from combined RADAR and passive microwave and sub-millimeter observations
#+AUTHOR:      Simon Pfreunschuh, Patrick Eriksson, Stefan Buehler, Manfred Brath, @@latex:\\@@ David Duncan, Robin Eklund
#+EMAIL:       simon.pfreundschuh@chalmers.se
#+OPTIONS: toc:nil
#+LaTeX_HEADER: \usepackage{natbib}
#+LaTeX_HEADER: \usepackage{siunitx}
#+LaTeX_HEADER: \usepackage{subcaption}
#+LaTeX_HEADER: \DeclareMathOperator\arctanh{arctanh}

  
* Introduction

   Ice clouds are an important component of the Earth's atmosphere and as such
   affect its weather and climate. Through reflection of incoming short-wave
   radiation and outgoing long-wave radiation, ice clouds influence the Earth's
   energy budget. Furthermore, due to their role in the global hydrological
   cycle and because of their relation to the dynamics of the atmosphere,
   observations of ice clouds provide important information to constrain the
   state of the atmosphere in forecasting models citep:geer or to validate
   predictions from climate models citep:waliser09.

   Despite the importance of observations of ice clouds for climate and weather
   prediction, the insufficiency of the current, global earth observation system
   to provide accurate information on concentrations of ice in the atmosphere
   has been put forward by several studies citep:eliasson11,duncan18a.
   Ultimately, this insufficiency is rooted in the large variability of
   concentrations, shapes and sizes in which ice in the atmosphere occurs,
   making it very difficult to accurately determine bulk-properties such
   as mass or number density using remote sensing techniques.

   The sensitivity of a remote sensing system to ice particles of given size is
   determined mainly by its observing frequencies. The interaction of radiation
   with ice particles is strongest for sizes roughly equal to the wavelength
   $\lambda$ of the radiation but decreases rapidly for smaller sizes. On the
   other hand, particles larger than one wavelength interact with the radiation
   strong enough that their presence quickly leads to saturation of the signal
   and thus loss of sensitivity inside and at the bottom of clouds.

   Since radiation at different frequencies is sensitive to ice crystals of
   different sizes, combining observations from across the electromagnetic
   spectrum can improve retrievals, allowing a larger part of the ice to be
   actively sensed as opposed to inferred based on a priori assumptions on the
   distribution of particle sizes. Even the combination of different types of
   observations at similar wavelengths, for example active and passive, can
   potentially improve a retrieval by providing additional information on the
   background state of the atmosphere.

   Of recent satellite missions that observe clouds, the A-train satellite
   constellation is certainly the most prominent. The constellation comprises
   several active and passive sensors observing the Earth only few minutes apart
   and has led to great advances in our ability to observe atmospheric ice at
   global scale. In particular, the CloudSat citep:stephens02 mission carrying
   the Cloud Profiling Radar (CPR, cite:tanelli08) has delivered unprecedented
   observations of the vertical distribution of ice in the atmosphere
   citep:austin09. Yet still, even the vertically resolved observations from a
   cloud radar possess only limited sensitivity to small ice particles and are
   unable to discern cloud microphysical properties. The low sensitivity of
   CloudSat to thin ice clouds has lead to the development of synergetic
   retrievals that combine CPR observations with other A-train sensors. The
   DARDAR-CLOUD citep:cazenave18 and CloudSat 2C-Ice citep:deng15 products, for
   example, both combine CPR observations with observations from the
   Cloud-Aerosol Lidar with Orthogonal Polarization (CALIOP, cite:winker07) to
   increase sensitivity to thin Cirrus clouds.

   Another perspective on ice particles in the atmosphere is provided by the
   Global precipitation measurement (GPM) mission citep:hou14. The backbone of
   the GPM mission is formed by its core observatory satellite, which carries
   the Dual-frequency Precipitation Radar (DPR) and the GPM Microwave Imager (GMI).
   Combined observations from DPR and GMI are used to retrieve vertically
   resolved concentrations of precipitating, liquid and frozen hydrometeors. The
   precipitation profiles retrieved from the combined active and passive
   observations from the core observatory are then used to constrain
   the passive-only precipitation profile retrievals from the other passive
   radiometers in the constellation citep:kummerow15.

   By virtue of their observing frequencies, the combined A-train products
   mentioned above and GPM essentially measure different types of atmospheric
   ice. CloudSat CPR observations, when combined with observations from the IR
   and optical regime ($\lambda < \SI{10}{\micro \meter}$) are best suited for
   the observation of comparably small, non-precipitating ice particles,
   typically referred to as cloud ice. The passive radiometers of the GPM
   constellation, are limited in their sensitivity to large, precipitating
   particles due to their limitation to microwave frequencies at and below
   $\SI{187}{\giga \hertz}$ ($\lambda < \SI{16}{\milli \meter}$).

   With the launch of the Ice Cloud Image (ICI) on board the second generation
   of meteorological, operational, polar-orbiting satellites (MetOp SG) planned
   from 2022, a new frequency range will become available to study ice in the
   troposphere. ICI will provide observations at 22 channels ranging from $187$
   to $\SI{664}{\giga \hertz}$ in frequency ($\SI{16}{\milli \meter} \leq
   \lambda \leq \SI{0.45}{\milli \meter}), and thus close the gap between
   observations in the traditional microwave region on the one hand and IR and
   optical observation on the other.

   Both, the A-train-based and GPM synergetic retrievals, demonstrate the
   potential of combining observations at different wavelengths as well as
   observations from active and passive sensors to improve the measurements of
   atmospheric ice from space. With the upcoming launch of ICI on board the
   MetOpSG satellites a new frequency range will become available to observe ice
   in the atmosphere and with that new opportunities for synergistic
   retrievals combining sub-millimeter observations with observations from other
   domains of the electromagnetic spectrum.

   While several studies so far have addressed the information content
   of sub-millimeter observations citep:grutzun18,birman17, only one
   early study on sub-millimeter radiometry citep:evans98 considers the
   combination with radar observations.

   In this study, we set out to investigate the potential of synergistic
   retrievals that combine ICI observations with that of a CPR-type cloud
   radar and additional passive microwave channels from the Microwave Imager
   (MWI), that will be flown together with ICI. In particular, we address
   the question to which extent complementary information content of the combined
   observations can help to constrain cloud microphysics. Furthermore, the
   technical feasibility of such retrievals is demonstrated by presenting a
   variational retrieval algorithm which is applied to retrieve cloud properties
   from simulated observations of cloud scenes from high-resolution climate
   model data.


* Methods and data

  This study aims to investigate the potential of synergistic retrievals of ice
  hydrometeors using observations from the ICI and MWI passive radiometers
  combined with a hypothesized W-band cloud radar. For this, cloud scenes from a
  high-resolution climate model are used to produce synthetic observations using
  radiative transfer simulations. The combined cloud retrieval algorithm is then
  applied to the synthetic observations and results compared to the reference
  cloud scenes.

  This section introduces the reference cloud scenes and the radiative transfer
 code used to generate the synthetic observations. This is followed by a
 description of the assumed sensor setup and the cloud retrieval algorithm.

** Reference cloud scenes

    As test scenes for the cloud retrieval, high-resolution climate model data
    from the Global Environmental Multiscale Model (GEM, cite:cote98) are used.
    The scenes have been produced for a validation campaign for the upcoming
    EarthCare satellite mission and can thus be expected to represent clouds
    with a degree of realism that is sufficient for the development and
    evaluation of a cloud retrieval algorithm. The use of model scenes as test
    data has the advantage of providing full knowledge and control of the true
    atmospheric state and thus allow for accurate characterization of retrieval
    performance. An overview over the two test scenes that will be used to test
    the retrieval is given in Figure \ref{fig:overview}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/scene_overview.png}
    \caption{The distribution of total hydrometeor mass content in the two
    cloud scenes used to test the retrieval. Colored lines show the
     $m = 10^{-5} \SI{}{\kg \per \meter \cubed}$ contour for different
     hydrometeor species.}
    \label{fig:overview}
    \end{figure}

    The GEM model uses the Milbrandt-Yau two-moment scheme citep:milbrandtyau05
    to predict distributions of liquid and frozen particles in the atmosphere.
    Clouds and precipitation are represented using 6 different hydrometeor
    classes: two liquid (rain and liquid cloud particles) and four
    frozen types (cloud ice, snow, hail and graupel). The bulk-microphysics
    scheme used in the model predicts number and mass density for each of the
    hydrometeor species. From the number and mass concentrations the full
    particle size distribution (PSD) can be prognosed using a species-dependent
    parametrization and mass-size relationship. To visualize the microphysical
    assumptions for the frozen hydrometeors, radomly-drawn realizations of
    particle size distributions from the test scenes together with
    the particle shapes are shown in Figure \ref{fig:gem_psds}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/gem_hydrometeors.png}
    \caption{Realizations of particle size distributions from the cloud scenes used in
    this study. Grey curves show 100 particle size distributions drawn randomly from
    grid points with a mass concentration higher than $10^{-6}$. Colored curves show the
    PSD for the prognosed for the mean of the 100 randomly drawn number and mass
    concentrations.}
    \label{fig:gem_psds}
    \end{figure}

** Radiative transfer simulations

   Version 2.3.1243 of the Atmospheric Radiative Transfer Simulator (ARTS,
   cite:arts18) is used for all simulations presented in this study. ARTS has
   recently been extended with a single-scattering radar solver that can be used
   to simulate radar reflectivities. Likewise, interfaces to state-of-the-art
   scattering solvers for the simulation of passive radiances in cloudy
   atmospheres have been added. Together with the recently developed ARTS single
   scattering database citep:ssdb,eriksson18, ARTS has grown to become an
   integrated tool for the study of of microwave and sub-millimeter observations
   of clouds. A recent closure study using CloudSat CPR and GMI observations has
   shown that ARTS is capable of reproducing the scattering signal observed from
   clouds at high microwave frequencies ($\SI{183}{\giga \hertz}$),
   demonstrating ARTS' capability produce realistic simulations of clouds
   observed at microwave frequencies.
   
   For the simulation of passive radiances, a hybrid solver is used that combines
   the DISORT scattering solver to simulate scattering interaction of radiation
   with cloud particles and ARTS built-in line-by-line solver. Simulations
   are performed assuming an ocean surface with emissivities calculated using
   the TESSEM sea-surface emissivity model. Polarization is neglected in all
   simulations performed in this study.
   

** Sensor configuration
\label{sec:sensors}
   
  The sensor configuration for the combined retrieval consists of a W-band cloud
  radar and the ICI and MWI radiometers. To simplify the modeling of the
  radiative transfer, the beams from all three instruments channels are assumed
  to be perfectly coincident pencil beams.

  ICI observations are simulated by performing a single, non-polarized radiative
  transfer simulation located at the center of each side band and averaging the
  resulting brightness temperatures. Only a single simulation is performed for
  channels with multiple polarizations, but to compensate the noise of the
  corresponding channel is reduced by a factor of $\sqrt{2}$.

  MWI observations are simulated in a similar manner, but using only channels
  with frequencies larger than or equal to $\SI{89}{\giga \hertz}$, due the very
  large footprint of the lower-frequency channels.

  For both, MWI and ICI, an off-nadir viewing angle of $\SI{48}{\degree}$ is
  assumed. The frequencies of the channels simulated for ICI and MWI are
  presented in table \ref{tab:channels}.

      \begin{table}[hbpt]
      \caption{Simulated channels of the MWI and ICI radiometers.}
      \label{tab:channels}
      \begin{subtable}[t]{0.45\textwidth}
      \caption{MWI}
          \resizebox{\textwidth}{!}{%
          \begin{tabular}{c|r|r}
          Channel & Freq. [GHz] & Noise [K]\\
          \hline
          MWI-8  & $89$              & $1.1$ \\
          MWI-9  & $118.75 \pm 3.2$  & $1.3$ \\
          MWI-10 & $\pm 2.1$         & $1.3$ \\
          MWI-11 & $\pm 1.4$         & $1.3$ \\
          MWI-12 & $\pm 1.2$         & $1.3$ \\
          MWI-13 & $165.5 \pm 0.75$  & $1.3$ \\
          MWI-14 & $183.31 \pm 7.0$  & $1.2$ \\
          MWI-15 & $ \pm 6.1$        & $1.2$ \\
          MWI-16 & $ \pm 4.9$        & $1.2$ \\
          MWI-17 & $ \pm 3.4$        & $1.2$ \\
          MWI-18 & $ \pm 2.0$        & $1.3$ \\
          \end{tabular}%
          }%
      \end{subtable}\hfill
      \begin{subtable}[t]{0.45\textwidth}
      \caption{ICI}
          \resizebox{\textwidth}{!}{%
          \begin{tabular}{c|r|r}
          Channel & Freq. [GHz] & Noise [K] \\
          \hline
          ICI-1  & $183.31 \pm 7.0$ & $0.8$\\
          ICI-2  & $       \pm 3.4$ & $0.8$\\
          ICI-3  & $       \pm 2.0$ & $0.8$\\
          ICI-4  & $243    \pm 2.5$ & $\frac{0.7}{\sqrt{2}}$\\
          ICI-5  & $325.15 \pm 9.5$ & $1.2$\\
          ICI-6  & $       \pm 3.5$ & $1.3$\\
          ICI-7  & $       \pm 1.5$ & $1.5$\\
          ICI-8  & $448    \pm 7.2$ & $1.4$\\
          ICI-9  & $       \pm 3.0$ & $1.6$\\
          ICI-10 & $       \pm 1.4$ & $2.0$\\
          ICI-11 & $664    \pm 4.2$ & $\frac{1.6}{\sqrt{2}}$\\
          \end{tabular}}
      \end{subtable}
      \end{table}

     The frequency for the cloud radar is chosen to be $\SI{94}{\giga\hertz}$
     similar to CloudSat CPR with a vertical resolution of $\SI{500}{\meter}$
     ranging from $0$ to $\SI{20}{\kilo \meter}$ in altitude. The minimum
     sensitivity is assumed to be $-\SI{30}{\deci \bel}\text{Z}$ and the noise
     at each range gate is assumed independent with standard deviation $0.5$.
     For simplicity, the same incidence angle as for the passive radiometers is
     used, assuming the radar observations at nadir can be remapped to the lines
     of sights of the passive beams.

** Retrieval algorithm

   The proposed 1-dimensional, variational cloud retrieval algorithm uses the
   optimal estimation formalism developed by cite:rodgers00. This means that the
   retrieved state $\mathbf{x} \in \mathrm{R}^n$ is determined by fitting a
   forward model $F : \mathbf{R}^n \rightarrow \mathbf{R}^m$ to a set of
   observations $\mathbf{y} \in \mathrm{R}^m$. The best fit is determined by
   minimizing a cost function of the form

    \begin{align}
    l(\mathbf{x}, \mathbf{y}) \propto
     \left(\mathbf{F}(\mathbf{x} - \mathbf{y} \right )
      \mathbf{S}_e^{-1} 
      \left ( \mathbf{F}(\mathbf{x}) - \mathbf{y} \right)
    + \left ( \mathbf{x} - \mathbf{x}_a \right )
     \mathbf{S}^{-1}_a 
     \left ( \mathbf{x} - \mathbf{x}_a \right ),
    \end{align}

    which corresponds to the negative log-likelihood of the Bayesian a
    posteriori distribution of the state $\mathbf{x}$ assuming zero-mean
    Gaussian measurement error with covariance matrix $\mathbf{S}_e$ and
    Gaussian a priori distribution with mean $\mathbf{x}_a$ and covariance
    matrix $\mathbf{S}_a$.

    The retrieved joint observation vector $\mathbf{y}$ consists of the
    concatenated observation vectors from each of the instruments:

     \begin{align}
     \mathbf{y} &= \left [ \begin{array}{c} \mathbf{y}_\text{MWI} \\ 
     \mathbf{y}_\text{ICI} \\ \mathbf{y}_\text{CPR} \end{array} \right ] 
     \end{align}

     Measurement errors are assumed to be independently Gaussian-distributed
     with standard deviations according to the noise characteristics given
     in Section \ref{sec:sensors}.

    The retrieved atmospheric state $\mathbf{x}$ consists of the distribution
    of a liquid and a frozen hydrometeor species and atmospheric humidity along
    a 1-dimensional atmospheric column coincident with the antenna beams.

    To represent the distributions of hydrometeors in the atmospheric column the
    normalized modified gamma distribution approach proposed by cite:delanoe05
    is used. This means that at each grid point the distribution of a given
    hydrometeor species is defined by its concentration coefficient $N_0^*$ and
    corresponding mass-weighted mean size diamter $D_m$. For the shape
    parameters $\alpha$ and $\beta$ for frozen hydrometeors the same values as
    in version 2 of the DARDAR-CLOUD product citep:cazenave18 are used. For
    liquid hydrometeors, the shape parameters are chosen so that they are
    equivalent to the shape used by the GEM model for rain drops. Figure
    \ref{fig:psds_retrieval} displays the resulting PSD shapes and corresponding
    parameter values.

    \begin{figure}
    \centering
    \includegraphics[width = 0.5\textwidth]{../plots/psds_retrieval}
    \caption{PSD parametrizations for frozen and liquid hydrometeors
     used in the cloud retrieval.}
    \label{fig:psds_retrieval}
    \end{figure}

    For frozen hydrometeors, the temperature-dependent a priori mean state
    is determined using the relation from cite:delanoe14:
    
    \begin{align}
    N_0^* &= \exp (-0.076586 \cdot t + 17.948)
    \end{align}
    
    The a priori state for $D_m$ for frozen hydrometeors is chosen so that the a
    priori mass density is equal to 
    $10^{-5} \SI{}{\kilo \gram \per \cubic \meter}$
    For liquid hydrometeors, a fixed value for $N_0^*$ of
    $10^6\si{\raiseto{4} \meter}$ is assumed and the a priori profile for $D_m$
    is determined similarly as for frozen hydrometeors
    
    As additional constraints, the retrieval of frozen hydrometeors is
    restricted to the region between the $\SI{0}{\celsius}$ -isotherm and
    tropopause and retrieval of liquid hydrometeors to below the
    $\SI{0}{\celsius}$ isotherm.
    
    Relative humidity in the atmospheric column is retrieved applying an
    inverse hyperbolic tangens transformation of the form:
    
    \begin{align}
    x = \arctanh(\frac{2 \phi}{1.1} - 1.0)
    \end{align}

    The transformation restricts the retrieved relative humidity values to
    the physical range of $[0.0, 1.1]$. 
    
    The a priori distributions of the 5 retrieval quantities ($N_0^*$ and $D_m$
    for frozen and liquid hydrometeors and relative humidity $\phi$) are assumed
    to be independent so that the overall a priori covariance matrix
    $\mathbf{S}_a$ has block-diagonal structure. Within each block, spatial
    correlations between grid points are assumed to be exponentially decaying.
    Hence, the correlation between grid points $i$ and $j$ of the values of the
    retrieval quantity $q$ are computed as
    
    \begin{align}
    \left ( \mathbf{S}_{a,q} \right )_{i, j} &= \sigma_{q,i} \sigma_{q,j}
     \cdot \exp ( \frac{d(i, j)}{l_q}),
    \end{align}
    where $\sigma_{q, i}$ is the a priori uncertainty assumed for retrieval
    quantity $q$ at grid point $i$, $d(i, j)$ the distance between the grid
    points and $l_q$ the quantity-specific correlation length. The assumed
    a priori uncertainties and correlation lengths for the retrieval quantities
    are summarized in Table \ref{tab:a_priori}.


      \begin{table}[h!]
      \caption{A priori uncertainties and correlation
       lengths used in the retrieval.}
       \centering
      \label{tab:a_priori}
          \begin{tabular}{c|r|r}
           Quantity $q$ & $\sigma_q$ & $l_q$ [km]\\
          \hline
          $\log(N_{0, \text{frozen}}^*)$    & $1$                       & $2$ \\
          $D_{m, \text{ice}}$               & $\SI{200}{\micro \meter}$ & $2$ \\
          $\log(N_{0, \text{liquid}}^*)$    & $1                      $ & $2$ \\
          $D_{m, \text{liquid}}$            & $\SI{500}{\micro \meter}$ & $2$ \\
          $\arctanh(\frac{2 \cdot \phi}{1.1} - 1.0)$ & $2$                       & $2$ \\
          \end{tabular}
      \end{table}

  As reference for the combined retrieval, also a passive-only retrieval is
  performed. This retrieval uses the combined retrieval with the exception that
  instead of regularizing the retrieval using spatial correlations, the vertical
  resolution of the retrieval grids is reduced. For ice, $N_0^*$ and *$D_m$ are
  retrieved on two and five equally spaced points between
  $\SI{0}{\celsius}$ -isotherm and troposphere, respectively. For liquid
  hydormeteors, the retrieval grids for $N_0$ and $D_m$ are reduced to three
  equally spaced points between surface and $\SI{0}{\celsius}$ -isotherm.
  Relative humidity is retrieved on 10 grid points between surface and
  tropopause.
    
   
* Results


In this section, results of a information content study are presented, that was
conducted in order to gain a better understanding of the synergies between
active and passive microwave observations. In addition to that, the results of
the cloud retrieval algorithm applied to the model cloud scenes are presented.

** Combined information content

   In order to explore the complementary information content in
   radar and radiometer observations, we consider an idealized,
   homogeneous cloud layer of thickness of $\SI{4}{\kilo meters}$ located
   at an altitude of $\SI{10}{\kilo\meter} in a tropical atmosphere. The
   cloud is assumed to consist of a single frozen hydrometeor species
   using the same PSD parametrization as the frozen hydrometeors used
   in the cloud retrieval (c.f. Figure \ref{fig:psds_retrieval}).
   
   As a first step, we want to address the question to what extent the active
   and passive observations can constrain the two moments of the PSD of the
   frozen hydrometeors. To this end, a range of simulated observations of the
   idealized cloud layer has been performed while the $N_0^*$ and $D_m$
   parameters of the PSD were varied. Figure \ref{fig:isolines} displays the
   contours of the simulated cloud signal, i.e. the brightness temperature
   difference between clear sky and cloudy sky simulation, n mass-$D_m$ space
   for a selection of channels of the MWI and ICI sensors. These are overlaid
   with isolines of the simulated radar reflectivity at the center of the cloud.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/contours}
    \caption{Simulated observations of a homogeneous cloud layer with
    varying mass density $m$ and mass-weighted mean diameter $D_m$. The panels
    display the radar reflectivity in dBZ at the cloud center overlaid on the
    cloud signal measured by selected radiometer channels of the MWI radiometer
    (first row) and the ICI radiometer (second row).}
    \label{fig:isolines}
    \end{figure}

    A necessary requirement for a passive channel to provide complementary
    information to the radar observation to resolve $N_0^*-D_m$ ambiguities is
    that the cloud signal contours and the radar isolines cross each other. The
    panels in Figure~\ref{fig:isolines} thus give an indication to what extent
    the information in the radar measurement and the corresponding passive
    channel provide complementary information on the $N_0^*$ and $D_m$
    parameters of the PSD. Considering the panels corresponding to the MWI channels,
    the results indicate complementary information only for regions of very
    strong cloud signal in radar and radiometer obervations. Compared to that,
    the ICI observations display a lower degree of parallelism, indicating
    higher complementary information content.

    The second question we address is the effect of ice particle shape on the
    observations. To do this, the simulations of the homogeneous cloud layer
    were repeated for the 15 \textit{standard habits} of the ARTS SSDB and a
    principal component analysis performed on the simulated observations. The
    first two eigenvectors of the covariance matrix are displayed in Figure
    \ref{fig:pca_ev}. The two displayed eigenvectors show the two principal axes
    of variability in the combined measurement space due to variation of the
    cloud parameters. The first eigenvector represents an increase of of the
    radar backscatter but a decrease over all radiometer channels and can thus
    be associated with the scattering of upwelling thermal radiation by the ice
    hydrometeors. The second eigenvector represents a decrease in radar
    reflectivity and a decrease in the radiometer channels except for ICI
    channels above $\SI{200}{\giga \hertz}$. The negative effect on the radar
    signal can be associated with the attenuation of the signal. For the
    radiometer channels below $\SI{200}{\giga \hertz}$ a likely explanation is
    the absorption of upwelling radiation. For the high frequency channels the
    positive effect on the measurement must be associated with emission in front
    of a radiometrically cold background.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/pca_evs}
    \caption{Components of the first two eigenvectors of the covariance
     matrix of the simulated observations of a homogeneous cloud layer with
     varying particle concentrations, sizes and shape.}
    \label{fig:pca_ev}
    \end{figure}

    By projecting the simulation results on the two PCA eigenvectors, a
    2-dimensional representation of each simulated observation is obtained.
    This allows all simulation results for a given particle shape to be
    visualized using a scatter plot. Figure \ref{fig:pca_e} displays three
    of such scatter plots for three particle habits. In addition to the results
    for obtained from a PCA performed on the full combined measurement vector
    (first row), the Figure also displays the results obtained when only
    the MWI channels and radar observations are used.

    Considering the first row of panels, the color coding of the markers
    clearly shows that the combined observations allow a separation of
    the effects of increases in the mass weighted mean size ($D_m$) and the
    particle concentration, which is proportional to the mass. This also
    confirms the interpretation of the first two PCA eigenvectors as related
    to scattering and emission/absorption effects, respectively.
    
    Comparing the first and second row of panels, the results also show that
    there is little complementary information on mean particle size and
    number concentration between the MWI channels and the radar.
    
    By comparing the distribution of the measurement results in the reduced
    measurement space, a clear effect of the particle shape on the measurement
    results can be distinguished. Unfortunately, since the distributions still
    have considerable overlap, it is not possible, at least based on this
    simple analysis, to separate the effects of particle shape and bulk particle
    size and concentration. Scatter plots for all SSDB standard habits are
    provided as a digital supplement to this article.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/pca_e}
    \caption{Scatter plots of the measurement results in the reduced
     measurement spaced spanned by the two first PCA eigenvectors for
     different ice particle habits. The first row displays the results obtained
     from a PCA using observations from the clouds radar and both radiometers
      (MWI and ICI), whereas the second row shows the results obtained from a
      PCA based solely on MWI and radar observations.}
    \label{fig:pca_ev}
    \end{figure}

** Retrieval performance

   To assess the performance of the combined cloud retrieval, the algorithm has
   been applied to retrieve ice hydrometeor distributions from the two model
   test scenes. For comparison, similar retrievals have been performed with a
   radar-only and a passive-only version of the algorithm. The retrieved ice
   mass density distribution for the three retrieval algorithms together with
   the sum of the reference mass densities of all frozen hydrometeors in the
   test scene are presented in Figure \ref{fig:results_md_1}.

   Since the passive-only retrieval is performed at reduced vertical resolution,
   these results clearly stand out, as they succeed to capture only the very
   coarse structure of the cloud. Comparing this to the radar-only results,
   the strength of the cloud radar to reproduce the vertical structure of the
   cloud is evident. Nonetheless, in particular in the upper parts of the
   cloud, the radar-only retrieval tends to underestimate the ice mass density
   concentrations.

   From the vertical resolution of the combined retrieval
   results, it is obvious that the combined retrieval benefits immensely from
   the vertically-resolved observations provided by the radar. Even though
   the results of the combined retrieval look very similar to those of the
   radar-only retrieval, in particular in the upper part of the cloud 
   regions where the mass density retrieval is improved are clearly visible.

   While the combined retrieval seems to work well in the outer parts of the
   cloud, it performs poorly in the region of very high ice mass concentrations
   at the center of the cloud. This is, however, not very surprising since the
   retrieval was designed for moderate ice mass density concentrations, where
   multiple scattering can be neglected. The bad quality of the retrieval
   in these regions is also reflected in the high values of the OEM cost
   function shown in the top panel of Figure~\ref{fig:results_md_1}.

    \begin{figure}
    \centering
    \includegraphics[width = \textwidth]{../plots/retrieval_results_a}
    \caption{Retrieval results for the first reference cloud scene.}
    \label{fig:pca}
    \end{figure}

    
    

* Discussion




* Conclusion
   
    


bibliographystyle:apalike 
bibliography:/home/simonpf/papers/references.bib
